server:
  port: 1111
  context-path: /client
  
security:
  oauth2:
    client:
      client-id: myapp
      client-secret: myappsecret
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      scope: server   
      authentication-scheme: form 
    resource:
      user-info-uri: http://localhost:9999/me